FHIR R4 MedicationStatement & PractitionerRole
d4l-data4life/hc-fhir-sdk-java pull request #29
Opened 2021-03-26 12:54 UTC by salehgamil

### What changed in this PR? 

- added MedicationStatement & PractitionerRole to the R4 Model
- adjusted The ObservationTests & LocationTests to fit changes in the newly generated examples
- removed any filed starting with an "_" from the examples

2021-03-26 15:31 UTC, me-d4l commented
@salehgamil Is it expected that there are no automatically generated test for MedicationStatement?

2021-03-28 17:12 UTC, salehgamil commented
> @salehgamil Is it expected that there are no automatically generated test for MedicationStatement?

It looked a bit odd to me, but I double checked before creating the PR. A test for the PractitionerRole was created but not for the MedicationStatement, even though they were both created following the exact same procedure, so I assumed this was expected.

2021-04-07 17:42 UTC, bitPogo requested changes
I guess you still need to hook the new resources into the `FhirElementFactory`, otherwise we cannot use them in the SDK.

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Timing.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Timing.java
> +     * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/Timing) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Substance.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Substance.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Specimen.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Specimen.java
> +     * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/Specimen) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Resource.java
> - * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Resource.java
> + * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/Resource) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Patient.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Patient.java
> +     * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/Patient) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Observation.java
> +     * Guidance on how to interpret the value by comparison to a normal or recommended range.  Multiple reference ranges are interpreted as an "OR".   In other words, to represent two distinct target
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Observation.java
> +     * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/Observation) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/MedicationStatement.java
> +        }
Is this branch necessary? Also I am not sure, what the comment should exactly tell me - so it might be worth to make it more clear.

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Location.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Location.java
> +     * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/Location) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Goal.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Goal.java
> +     * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/Goal) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Encounter.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/Encounter.java
> +     * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/Encounter) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/CareTeam.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/CareTeam.java
> +     * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/CareTeam) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/CodeSystem.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/CodeSystem.java
> +     * Generated from FHIR 4.0.1-9346c8cc45 (http://hl7.org/fhir/StructureDefinition/CodeSystem) on 2021-04-07
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/DocumentReference.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-07 17:42 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/DocumentReference.java
> -     * <p>
Why is here the paragraph deleted?

2021-04-08 07:50 UTC, wmontwe commented
@salehgamil I will reformat the code and push this as an update to this pull-request

2021-04-08 08:26 UTC, wmontwe commented
> I guess you still need to hook the new resources into the `FhirElementFactory`, otherwise we cannot use them in the SDK.

Will do

2021-04-08 13:21 UTC, bitPogo commented on fhir-java/src-gen/main/java/care/data4life/fhir/r4/model/MedicationStatement.java
> +        }
A nitpick: @wmontwe

2021-04-08 14:32 UTC, bitPogo approved these changes
LGT

2021-04-08 14:33 UTC, merged